### ISSUE TITLE
Find a way to get TravisCI working with NightOwl

### ISSUE THREAD

**Issue by Ahmad-Bamba** [Chantilly612Code/NightOwl#1]
Because this is a library, the compiler will always complain that there's no main, because we never START_ROBOT_CLASS(...); This means that the current TravisCI setup in 612-2016 won't unless we change it some for this

**Comment by ZackAlfakir** [comment]
Try the -c compiler flag for gcc

**Comment by ZackAlfakir** [comment]
Fixed with #3
