### ISSUE TITLE
Change FlexiblePID to Flexible I/O classes which are compatible with the existing, working PID code

### ISSUE THREAD

**Issue by Ahmad-Bamba** [Chantilly612Code/NightOwl#10]
Idk why I'm making this an issue when I'm just gonna do it. Formality I guess.

I was about to fix the error I made in the FlexiblePID class and I realized that the whole thing is really jank code that I copied and don't really understand. Harder to debug, harder for the end-user to use, its bad all the way around.

Essentially the Flexible I/O classes will allow you to add a function or an object into the constructor so that you don't need to have one of the [pre-approved classes](http://first.wpi.edu/FRC/roborio/release/docs/cpp/classPIDSource.html) to make the PIDController work.

**Comment by WardBenjamin** [comment]
What is the actual reason for this? PIDSource is trivial to implement and already lets you do everything that you need to do. I don't really see a justification for these "Flexible I/O" classes.

**Comment by WardBenjamin** [comment]
Closed as per discussion.
