### ISSUE TITLE
Remove extraneous PID fluff

### ISSUE THREAD

**Issue by WardBenjamin** [Chantilly612Code/NightOwl#11]
As per team discussion, we need to remove the extraneous PID classes, like FlexiblePID, because they're not useful, hard to test, and especially provide functionality that is already handled in PIDController, PIDSubsystem, and PIDCommand.

**Comment by Ahmad-Bamba** [comment]
"As per my personal opinion you need to do what I say"

**Comment by Ahmad-Bamba** [comment]
This has been resolved a long time ago
